SET NAMES UTF8;
DROP DATABASE IF EXISTS xuezi;
CREATE DATABASE xuezi CHARSET=UTF8;
USE xuezi;
CREATE TABLE user(
	uid INT PRIMARY KEY,
	uname VARCHAR(16),
	upwd VARCHAR(32)
);
INSERT INTO user VALUES(1,'TOM8','123456DF');
INSERT INTO user VALUES(2,'DAHAI8','TEE456DF');